# -*- coding: utf-8 -*-
"""Check For Naan Values.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sZUg5tQav9CQ1wjNW-pbLbf0YacSqXxu
"""

import pandas as pd
import numpy as np
import math

valuestocheck=[1, float("nan"), 3, float("nan"), "nan", "nan"]

iteration=0
stringnanlist=[]
nanvaluelist=[]

for value in valuestocheck:

  isnan=0

  try: 
    if pd.isna(value):
      isnan=1
  except:
    pass

  try:
    if np.isnan(value):
      isnan=1
  except:
    pass

  try:
    if math.isnan(value):
      isnan=1
  except:
    pass

  if value!=value:
    isnan=1

  try:
    if float('-inf') < float(num) < float('inf'):
      isnan=1
  except:
    pass
  
  if value == "nan":
    stringnanlist.append(iteration)

  if isnan > 0:
    nanvaluelist.append(iteration)

  iteration+=1

if len(nanvaluelist)==0:
  print("There are no nan values")
elif len(nanvaluelist)==1:
  print("There is 1 nan value, index number", nanvaluelist[0], "on the valuestocheck")
elif len(nanvaluelist)>1:
  print("There is", len(nanvaluelist), "nan values. Here are their index numbers on the valuestocheck:", [i for i in nanvaluelist])

if len(stringnanlist)==1:
  print("There is 1 string named nan, index number", stringnanlist[0], "on the valuestocheck")
elif len(stringnanlist)>1:
  print("There is", len(stringnanlist), "strings called nan. Here are their index numbers on the valuestocheck:", [i for i in stringnanlist])